!!python/object:__main__.Config
arities:
- 1
- 1
- 1
constants: []
forbidCycles: NEGATIVE
independentPairs:
- predicate1: p
  predicate2: q
- condition:
    operator: OR
    predicates:
    - p
    - q
  predicate1: p
  predicate2: r
- condition:
    operator: OR
    predicates:
    - p
    - q
  predicate1: q
  predicate2: r
maxNumClauses: 5
maxNumNodes: 5
predicates:
- p
- q
- r
requiredFormula:
  operator: OR
  predicates:
  - p
  - q
variables:
- X
