arities:
- 2
- 2
- 2
- 1
- 1
- 1
- 1
- 1
- 1
- 1
constants: []
forbidCycles: ALL
#independentPairs:
#- predicate1: p
#  predicate2: q
#- condition:
#    operator: OR
#    predicates:
#    - p
#    - q
#  predicate1: p
#  predicate2: r
#- condition:
#    operator: OR
#    predicates:
#    - p
#    - q
#  predicate1: q
#  predicate2: r
maxNumClauses: 10
maxNumNodes: 3
predicates:
- pa
- pb
- pc
- pd
- pe
- pf
- pg
- ph
- pi
- pj
#requiredFormula:
#  operator: OR
#  predicates:
#  - p
#  - q
variables:
- X
- Y
